# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a406d3510c5794f45520748904e0e322b1c00750a0887d8f721b2a0ab88093fdc206f34407f1c60ca6e29292c5b6c71d54bdb68228f9874bb94c30446758da9d

test:
  secret_key_base: c033bd42656bda202c48a6c030cccce212d1fd8e2348e0be9e18930d2b7441fcdb4e32ae8ef1a4db213b3f20c698a27c71244970d6de085e2a3864d5846cf44e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
